'use strict';

(function () {
  window.constants = {
    MAIN_ROUND_PIN_WIDTH: 35,
    MAIN_ROUND_PIN_HEIGHT: 35,
    MAIN_PIN_DEFAULT_X: 570,
    MAIN_PIN_DEFAULT_Y: 375,
    ESC_KEYCODE: 27,
    MAIN_PIN_WIDTH: 65,
    MAIN_PIN_HEIGHT: 87,
    MAP_HEIGHT_MIN: 130,
    MAP_HEIGHT_MAX: 630,
    PIN_WIDTH: 50,
    PIN_HEIGHT: 70,
    ENTER_KEYCODE: 13,
    SUCCESS_STATUS: 200,
    LOW_PRICE_BEFORE: 10000,
    MIDDLE_PRICE_BEFORE: 50000,
  };
})();
